### PR TITLE
To resolve the issue of running JSON Server and Vite Server separately

### PR DESCRIPTION
**Pull request by Durgesh63**
you are use different terminal instances or tabs to execute each server individually.

To resolve the issue of running JSON Server and Vite Server separately.

I do pull request for this changes.

Thankyou.

### CODE REVIEW

**Comment by Kuzma02** [comment]
Thank you Durgesh. I will merge it tomorrow because I need to update README and record new Youtube video with this change.

**Comment by Kuzma02** [comment]
Hello Durgesh. I have tested the project with new changes, but shop page doesn't show products. It only happens when I run "npm start". When I run with different terminal instances it works.
screencapture-localhost-5173-shop-2024-03-31-12_01_36

**Comment by Durgesh63** [comment]
Hello @Kuzma02 ,

Thanks for testing the project and letting me know about the issue with the shop page not showing products when running 'npm start'. I'll look into it and see if I can replicate the issue. Once I've investigated further and made any necessary changes, I'll redeploy the project and let you know. 

Thankyou

**Comment by Durgesh63** [comment]
Hello @Kuzma02 ,


Thanks for your patience. I've investigated the issue with the shop page not displaying products when running 'npm start' and have made the necessary changes. I kindly request you to review the modifications and consider merging the code. Let me know if you need any further assistance or clarification.

Here are some issues please have a look.

Shop Page Issue -->
Issue: In this scenario, there are multiple issues:
1. The _page variable needs adjustment to navigate to the next page.
2. There is a sorting issue.
3. If no parameter matches, an undefined value is added between two different parameters.
4. I will make changes to the filter page like  date  field and range price field for a smoother user experience.

Solutions:
 I used _start in place of _page , along with many other necessary changes. Please review.


Search Page Issue --> 
Issue: In this scenario, the map function is receiving undefined values.
Solution: I will add a check for undefined values and ensure that the variable iterates only over an array.

search page issue -
Screenshot from 2024-04-07 01-19-42

solve --
image


Shop Page -
image
image







Need for new Update :
There is a default date selection issue, making it difficult for users to select a specific date, especially beyond four years and need to implement date range filter.


Thankyou

**Comment by Kuzma02** [comment]
Excellent and well done @Durgesh63. There is only one problem with the search, but I have found a solution. The newest version of json-server "alpha v1" doesn't have the full-text search functionality that is needed for the search page to work. So the solution is to install a stable version of json-server instead of an alpha unstable version. So write the following and search will work: npm i json-server@0.17.4. Please install it and I will immediately merge everything.

**Comment by Durgesh63** [comment]
Hi @Kuzma02 ,

I've installed the stable version of json-server as per your instructions. You can confirm by checking the version installed, which should be 0.17.4. Once you verify, please proceed with merging everything. Let me know if there's anything else you need assistance with.

**Comment by Kuzma02** [comment]
Hi @Durgesh63,

Thank you for your patience and contribution. Everything is working and merged.

**Pull request merged**
